# Step 1 : Choose a Base Image
FROM alpine

# Step 2 : Install a software
RUN apk add binutils

# Step 2.5 : Configure the software
            # No configurations yet

# Step 3 : Set Default commands
CMD ['executable']